import "./globals.css";
import Providers from "./providers";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="transition-colors duration-500 bg-gray-200 dark:bg-gray-800">
        <Providers>
          {children}
          </Providers>
      </body>
    </html>
  );
}
